version: "3.5"

networks:
  db_network:
    driver: bridge
    name: ibook_db_access-${DOCKER_VOLUME_MODE:-dev}
    ipam:
      driver: default
    internal: ${DB_NETWORK_INTERNAL:-true}
  backend_network:
    driver: bridge
    name: ibook-backend-network-${DOCKER_VOLUME_MODE:-dev}
    internal: true
  production_network:
    name: ibook_production_proxy
    external: true
#  db_network: {}
#  backend_network: {}
#  production_network: {}


services:

  proxy:
    image: nginxproxy/nginx-proxy:alpine

  acme-proxy:
    image: nginxproxy/acme-companion:latest

  db:
    image: postgres:14-alpine3.14
    command: postgres -c max_connections=50 -c shared_buffers=80MB
    restart: ${DOCKER_RESTART_CONTAINER:-no}

    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_SUPERUSER_NAME}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      VIRTUAL_HOST: ${DB_VIRTUAL_HOST}
      VIRTUAL_PORT: ${DB_HOST_PORT}
    volumes:
      - postrges14_volume:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - '${DB_HOST_PORT:-5432}:5432'
    expose:
      - '${DB_HOST_PORT:-5432}'
  
  
  #  complete_migrations:

  backend:
    image: daniinxorchenabo/ibook_backend:${PYTHON_ENV_TAG:-latest}

    restart: ${DOCKER_RESTART_CONTAINER:-no}
    env_file:
      - .env
    
    environment:
      LETSENCRYPT_TEST: ${LETSENCRYPT_HTTPS_PROTOCOL_TEST:-true}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_HOST_PORT: ${DB_PORT:-5432}
      VIRTUAL_HOST: ${BACKEND_API_VIRTUAL_HOST}
      VIRTUAL_PORT: ${BACKEND_PORT_EXTERNAL:-5264}
      SSL_TYPE: letsencrypt
      LETSENCRYPT_HOST: ${BACKEND_API_VIRTUAL_HOST}
      DOCKER_RUN_FROM_DOCKER: 'true'
    depends_on:
      - db

    command: dotnet socialNetworkApp.dll --urls http://0.0.0.0:${BACKEND_PORT_INTERNAL:-6000}
    networks:
      - production_network
      - backend_network
      - db_network
    ports:
      - '${BACKEND_PORT_EXTERNAL:-80}:${BACKEND_PORT_INTERNAL:-6000}'
    expose:
      - ${BACKEND_PORT_EXTERNAL:-80}

  pgadmin:
    image: dpage/pgadmin4:5.7
    depends_on:
      - db
    restart: ${DOCKER_RESTART_CONTAINER:-no}

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      VIRTUAL_HOST: ${PGADMIN_VIRTUAL_HOST}
      VIRTUAL_PORT: ${PGADMIN_PORT}
    #      VIRTUAL_PROTO: https
    networks:
      - db_network
      - production_network
    ports:
      - '${PGADMIN_PORT}:80'
    expose:
      - '${PGADMIN_PORT}'
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  postrges14_volume:
    name: ibook_postrges14_volume-${DOCKER_VOLUME_MODE}
  pgadmin_volume:
    name: ibook_pgadmin_volume-${DOCKER_VOLUME_MODE}
  front_volume:
    name: ibook_front-${DOCKER_VOLUME_MODE}
